title: FileMaker Inventory Resources
author: Daniel Shanahan
email: support@newleafdata.com
description: > # this means to ignore newlines until "baseurl:"
  Articles and free demo files for business owners building their own inventory managnement app on the FileMaker platform.
baseurl: ""
twitter_username: jekyllrb
github_username:  jekyll
collections:
  articles:
    output: true
    permalink: /articles/:path
  files:
    output: true
    permalink: /files/:path

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
